### ISSUE TITLE
undefined method `before_filter' for Sextant::RoutesController:Class Did you mean?  before_action

### ISSUE THREAD

**Issue by cannyedge34** [schneems/sextant#42]
rails 5.1

Tahnks!

**Comment by schneems** [comment]
Check the readme. Sextant doesn’t work with Rails 5.1 you can remove the gem. The functionality was added directly into Rails.

**Comment by cannyedge34** [comment]
Thank a lot!

http://localhost:3000/rails/info/routes
